# Generated by Django 3.0.5 on 2020-04-03 09:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertimelog',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 4, 3, 9, 16, 42, 738149)),
        ),
        migrations.AlterField(
            model_name='usertimelog',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='usertimelog',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
