# Generated by Django 3.0.5 on 2020-04-03 09:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('userlog', '0002_auto_20200403_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertimelog',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 4, 3, 9, 18, 5, 260355, tzinfo=utc)),
        ),
    ]
