# Generated by Django 3.0.5 on 2020-04-03 09:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userlog', '0003_auto_20200403_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertimelog',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
