# Generated by Django 3.0.5 on 2020-04-07 06:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userlog', '0004_auto_20200403_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertimelog',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='usertimelog',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='usertimelog',
            name='end_time',
            field=models.TimeField(verbose_name='end time'),
        ),
        migrations.AlterField(
            model_name='usertimelog',
            name='start_time',
            field=models.TimeField(verbose_name='start time'),
        ),
        migrations.AlterField(
            model_name='usertimelog',
            name='title',
            field=models.CharField(max_length=64, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='usertimelog',
            name='username',
            field=models.EmailField(max_length=254, verbose_name='user name'),
        ),
    ]
